### ISSUE TITLE
使用HDFS存储数据，在iotdb-engine.properties中配置core_site_path无效

### ISSUE THREAD

**Issue by weicz1221** [apache/incubator-iotdb#970]
**Describe the bug**
想使用HDFS存储数据，在iotdb-engine.properties中core_site_path配置hadoop的core-site.xml路径无效，iotdb还是读取默认文件路径：/etc/hadoop/conf/core-site.xml

查看以下源码发现在TSFileDescriptor类中的没有loadProps方法中没有对coreSitePath和hdfs_site_path重新赋值，
![image](https://user-images.githubusercontent.com/49259303/78230388-d8bf7880-7503-11ea-942f-796283716e5f.png)

麻烦帮忙看一下是否是我自己的配置原因。

**Comment by samperson1997** [comment]
感谢您使用此功能！是代码中的笔误，我已经在 PR #973 中修复，您可以在您的当前版本拉取此 PR 再次尝试。如果在使用 HDFS 存储 TsFile 数据的过程中出现任何问题，欢迎随时与我联系！

Hi, Thanks for using this function. This is caused by a typo in code, and I have fixed it in PR #973 . You could pull this PR in your code version and try again. If you meet any confusion and problems in using function of storage TsFile on HDFS, please feel free to contact with me : )
